### ISSUE TITLE
Add Plats for Manasteel and Elementium

### ISSUE THREAD

**Issue by Ldmf** [combusterf/Botania-expert-backup#1]
adde paltes to Elementium and Manasteel
then replace all recepts that use thos ingots with plates

Modpack GTNH

![2022-01-11_14 25 26](https://user-images.githubusercontent.com/15316448/148951078-a440e458-67e6-4c67-ad8f-c06887a8920c.png)
![2022-01-11_14 25 30](https://user-images.githubusercontent.com/15316448/148951099-81a80eb3-2de1-48e5-b4f9-a94dfcd1ee52.png)
![2022-01-11_14 25 39](https://user-images.githubusercontent.com/15316448/148951126-3c774b7b-2721-491b-ada3-ddc854555d69.png)

**Comment by combusterf** [comment]
1: This is not the GT:NH repository
2: The people there are working on it.
